from django.db import models
from django.conf import settings
from multiselectfield import MultiSelectField

from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager)


class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, first_name, last_name, password=None):
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have an username")
        if not first_name:
            raise ValueError("Users must have an first name")
        if not last_name:
            raise ValueError("Users must have an last name")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, first_name, last_name, password=None):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
            first_name=first_name,
            last_name=last_name,
        )
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    email = models.EmailField(verbose_name='email address', max_length=60, unique=True)
    first_name = models.CharField(verbose_name='first name', max_length=30)
    last_name = models.CharField(verbose_name='last name', max_length=40)
    username = models.CharField(max_length=30, unique=True)
    phone = models.CharField(verbose_name='Phone', max_length=40, null=True, blank=True)
    profile_pic = models.ImageField(verbose_name='profile picture', null=True, blank=True)
    about_me = models.TextField(verbose_name='about me', max_length=250, null=True, blank=True)
    birth_day = models.DateField(verbose_name='birth_day', null=True, blank=True)
    living_city = models.CharField(verbose_name='living city', max_length=100, null=True, blank=True)
    gender = models.CharField(verbose_name='gender', max_length=1, choices=GENDER_CHOICES, default='M')
    website = models.CharField(verbose_name='website', max_length=100, null=True, blank=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = MyAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


class Specialization(models.Model):
    WORK_PREPAREDNESS = (
        ('1', 'Not looking for work'),
        ('2', 'Looking for work'),
        ('3', 'Open to offers'),
    )

    QUALIFICATION = (
        ('1', 'Intern'),
        ('2', 'Junior'),
        ('3', 'Middle'),
        ('4', 'Senior'),
        ('5', 'Lead'),
    )

    SPHERE = (
        ('1', 'Backend'),
        ('2', 'Frontend'),
        ('3', 'Design'),
        ('4', 'Administration'),
        ('5', 'Analytics'),
        ('6', 'Testing'),
        ('7', 'Management'),
        ('8', 'Marketing'),
        ('9', 'Telekom'),
        ('10', 'Sales'),
        ('11', 'Applications'),
        ('12', 'Software'),
        ('13', 'Other'),
    )

    SKILL = (
        ('1', 'ABAP'),
        ('2', 'ActiveMQ'),
        ('3', 'Ada programming'),
        ('4', 'Amazon Web Services'),
        ('5', 'Android'),
        ('6', 'Angular 2+'),
        ('7', 'AngularJS'),
        ('8', 'Ansible'),
        ('9', 'Apache Hive'),
        ('10', 'Apache Kafka'),
        ('11', 'Apache Pig'),
        ('12', 'Apache Spark'),
        ('13', 'ARM'),
        ('14', 'ASP.NET'),
        ('15', 'ASP.NET MVC'),
        ('16', 'Azure'),
        ('17', 'Backbone.js'),
        ('18', 'Bash'),
        ('19', 'Blockchain'),
        ('20', 'C'),
        ('21', 'C#'),
        ('22', 'C++'),
        ('23', 'CakePHP'),
        ('24', 'Cassandra'),
        ('25', 'Chef'),
        ('26', 'Cisco'),
        ('27', 'Clojure'),
        ('28', 'CoffeeScript'),
        ('29', 'Cordova'),
        ('30', 'Cross Platform Mobile'),
        ('31', 'Django'),
        ('32', 'Docker'),
        ('33', 'Drools'),
        ('34', 'Drupal'),
        ('35', 'Elasticsearch'),
        ('36', 'Elixir'),
        ('37', 'ELM'),
        ('38', 'Embedded Linux'),
        ('39', 'Ember.js'),
        ('40', 'Erlang'),
        ('41', 'ETL'),
        ('42', 'Ez Platform'),
        ('43', 'F#'),
        ('44', 'Flash'),
        ('45', 'Flask'),
        ('46', 'Flutter'),
        ('47', 'Fortinet'),
        ('48', 'Fortran'),
        ('49', 'FPGA'),
        ('50', 'Go'),
        ('51', 'Google Cloud Platform'),
        ('52', 'Google Data Studio'),
        ('53', 'Grails'),
        ('54', 'Grape'),
        ('55', 'Groovy'),
        ('56', 'Hadoop'),
        ('57', 'Haskell'),
        ('58', 'HBase'),
        ('59', 'Hibernate'),
        ('60', 'HTML/CSS'),
        ('61', 'Hyper-V'),
        ('62', 'Informatica'),
        ('63', 'Internet of Things'),
        ('64', 'Ionic'),
        ('65', 'iOS'),
        ('66', 'J2EE'),
        ('67', 'Java'),
        ('68', 'JavaFX'),
        ('69', 'JavaScript'),
        ('70', 'Jenkins'),
        ('71', 'Joomla'),
        ('72', 'jQuery'),
        ('73', 'Juniper'),
        ('74', 'Keras'),
        ('75', 'Kotlin'),
        ('76', 'Kubernetes'),
        ('77', 'LAN/WAN'),
        ('78', 'Laravel'),
        ('79', 'Liferay'),
        ('80', 'Linux'),
        ('81', 'Lisp'),
        ('82', 'Looker'),
        ('83', 'Magento'),
        ('84', 'Matlab'),
        ('85', 'Memcached'),
        ('86', 'Meteor'),
        ('87', 'MongoDB'),
        ('88', 'MySQL'),
        ('89', '.NET'),
        ('90', '.NET Core'),
        ('91', 'NLP'),
        ('92', 'Node.js'),
        ('93', 'Objective-C'),
        ('94', 'OCaml'),
        ('95', 'OpenGL'),
        ('96', 'OpenStack'),
        ('97', 'Oracle Database'),
        ('98', 'Pandas'),
        ('99', 'Pentaho'),
        ('100', 'Perl'),
        ('101', 'PHP'),
        ('102', 'Pixi.js'),
        ('103', 'Play'),
        ('104', 'PL/SQL'),
        ('105', 'Polymer'),
        ('106', 'PostgreSQL'),
        ('107', 'Power BI'),
        ('108', 'Prestashop'),
        ('109', 'Proxmox Virtual Environment'),
        ('110', 'Puppet'),
        ('111', 'Python'),
        ('112', 'Pytorch'),
        ('113', 'Qlik'),
        ('114', 'Qt'),
        ('115', 'R'),
        ('116', 'RabbitMQ'),
        ('117', 'ReactJS'),
        ('118', 'React Native'),
        ('119', 'Redis'),
        ('120', 'Redux'),
        ('121', 'Riot.js'),
        ('122', 'Ruby'),
        ('123', 'Ruby on Rails'),
        ('124', 'Rust'),
        ('125', 'SAS'),
        ('126', 'SASS'),
        ('127', 'Scala'),
        ('128', 'Scheme'),
        ('129', 'scikit-learn'),
        ('130', 'Selenium'),
        ('131', 'SEO'),
        ('132', 'Shopware'),
        ('133', 'Sinatra'),
        ('134', 'Solr'),
        ('135', 'Spring'),
        ('136', 'Spring Boot'),
        ('137', 'SPSS'),
        ('138', 'SQL'),
        ('139', 'SQL Server'),
        ('140', 'Stata'),
        ('141', 'Struts'),
        ('142', 'Swift'),
        ('143', 'Symfony'),
        ('144', 'Tableau'),
        ('145', 'Talend'),
        ('146', 'TCL'),
        ('147', 'TensorFlow'),
        ('148', 'Terraform'),
        ('149', 'Tomcat'),
        ('150', 'T-SQL'),
        ('151', 'TypeScript'),
        ('152', 'Unity'),
        ('153', 'Unix Shell Scripting'),
        ('154', 'VBA'),
        ('155', 'VB.NET'),
        ('156', 'Verilog'),
        ('157', 'VHDL'),
        ('158', 'VMWare vSphere'),
        ('159', 'Vue.js'),
        ('160', 'VxWorks'),
        ('161', 'WCF'),
        ('162', 'Windows'),
        ('163', 'Windows Mobile'),
        ('164', 'WordPress'),
        ('165', 'WPF'),
        ('166', 'x86 Assembly'),
        ('167', 'Xamarin'),
        ('168', 'Yii'),
        ('169', 'Zend Framework'),
        ('170', 'Microsoft Office Word'),
        ('171', 'Microsoft Office Excel'),
        ('172', 'Microsoft Office PowerPoint'),
        ('173', 'Microsoft Office Outlook'),
        ('174', 'Microsoft Office Project'),
        ('175', 'Microsoft Office Access'),
        ('176', 'Microsoft Office Visio'),
        ('177', 'Microsoft Office Sharepoint'),
        ('178', 'MS office applications'),
        ('179', '1C'),
        ('180', 'Active Directory'),
        ('181', 'Active Sync'),
        ('182', 'AD'),
        ('183', 'Adobe Acrobat'),
        ('184', 'Adobe after effects'),
        ('185', 'Adobe Audition'),
        ('186', 'Adobe Photoshop'),
        ('187', 'Adobe Premiere Pro'),
        ('188', 'Adobe Reader'),
        ('189', 'AJAX'),
        ('190', 'Android SDK'),
        ('191', 'Angular'),
        ('192', 'ANSYS'),
        ('193', 'Application Servers'),
        ('194', 'Arc GIS'),
        ('195', 'ArchiCAD'),
        ('196', 'Ariana'),
        ('197', 'ASP'),
        ('198', 'Asterisk'),
        ('199', 'Asterisk Server'),
        ('200', 'ASYCUDA'),
        ('201', 'AutoCAD'),
        ('202', 'AutoCAD Civil 3D'),
        ('203', 'Bootstrap'),
        ('204', 'Bulk Rename utility'),
        ('205', 'CATIA'),
        ('206', 'CMS'),
        ('207', 'Corel'),
        ('208', 'coreldraw'),
        ('209', 'Crystal Report'),
        ('210', 'CSS'),
        ('211', 'CSS3'),
        ('212', 'Data Deduplication'),
        ('213', 'Data warehouse'),
        ('214', 'Database performance tuning'),
        ('215', 'Devexpress'),
        ('216', 'DFS'),
        ('217', 'DHCP'),
        ('218', 'DNS'),
        ('219', 'eBudget'),
        ('220', 'Edge Server'),
        ('221', 'eDocument'),
        ('222', 'eflow'),
        ('223', 'eHRMS'),
        ('224', 'EJB 3.x'),
        ('225', 'Entity Framework'),
        ('226', 'eTreasury'),
        ('227', 'EViews'),
        ('228', 'Exchange'),
        ('229', 'Exchange Server'),
        ('230', 'Exchange(DAG)'),
        ('231', 'Ext JS'),
        ('232', 'extejs'),
        ('233', 'Fiber Optics'),
        ('234', 'Final Cut Studio'),
        ('235', 'Firewall'),
        ('236', 'Flexsys'),
        ('237', 'FMG'),
        ('238', 'FSRM'),
        ('239', 'FTP'),
        ('240', 'GeoServer'),
        ('241', 'Google Apps for Business'),
        ('242', 'GPO'),
        ('243', 'GPS'),
        ('244', 'Group policy'),
        ('245', 'Hibernate/JPA'),
        ('246', 'HTML'),
        ('247', 'HTML5'),
        ('248', 'IIS'),
        ('249', 'illustrator'),
        ('250', 'InDesign'),
        ('251', 'IPCC Inventory Software'),
        ('252', 'iSCSI '),
        ('253', 'JAVA EE'),
        ('254', 'java SDK'),
        ('255', 'Java Spring'),
        ('256', 'JBoss Aplication Server'),
        ('257', 'JBoss Seam Framework'),
        ('258', 'JMS'),
        ('259', 'JS'),
        ('260', 'JSF'),
        ('261', 'JSON'),
        ('262', 'Kerio Operator'),
        ('263', 'LINQ'),
        ('264', 'Lumion'),
        ('265', 'Lync'),
        ('266', 'Mac OS'),
        ('267', 'Magic X Audio Editing'),
        ('268', 'Magic X Music Macer'),
        ('269', 'Mail Server'),
        ('270', 'Max MSP'),
        ('271', 'MAXQDA'),
        ('272', 'Microsoft Active Directory'),
        ('273', 'Microsoft Exchange'),
        ('274', 'Microsoft Exchange 2013-2016'),
        ('275', 'Microsoft Exchange Servers Clustering'),
        ('276', 'Microsoft Expression Blend'),
        ('277', 'Microsoft Project Server'),
        ('278', 'Microsoft SQL Server Management Studio'),
        ('279', 'Microsoft Team Foundation Server '),
        ('280', 'Microsoft Visual Studio'),
        ('281', 'Mozilla Firefox'),
        ('282', 'Mplus'),
        ('283', 'MS Office Lync'),
        ('284', 'MS SQL'),
        ('285', 'MS SQL Server'),
        ('286', 'MVC'),
        ('287', 'MVC Core'),
        ('288', 'Mware vSphere 6.x'),
        ('289', 'Navision'),
        ('290', 'Network Administrator '),
        ('291', 'NTFS File Permission'),
        ('292', 'NVivo'),
        ('293', 'OneNote'),
        ('294', 'OOP'),
        ('295', 'OOP PHP'),
        ('296', 'Oracle'),
        ('297', 'Oracle 11g'),
        ('298', 'Oracle, XML'),
        ('299', 'ORIS'),
        ('300', 'ORIS Manager'),
        ('301', 'Outlook Anywhere '),
        ('302', 'Outlook Express'),
        ('303', 'PageMaker'),
        ('304', 'PDS'),
        ('305', 'Photoshop'),
        ('306', 'Power IP PBX Systems'),
        ('307', 'Premier Pro'),
        ('308', 'Project Server'),
        ('309', 'Publisher'),
        ('310', 'RA'),
        ('311', 'Revit'),
        ('312', 'RichFaces'),
        ('313', 'RichFaces/MyFaces'),
        ('314', 'Routing'),
        ('315', 'RS.GE'),
        ('316', 'SCCM'),
        ('317', 'SCDPM'),
        ('318', 'SCO'),
        ('319', 'SCOM'),
        ('320', 'SCVMM'),
        ('321', 'Share Permission'),
        ('322', 'SharePoint'),
        ('323', 'Sony Vegas'),
        ('324', 'Sound Forge'),
        ('325', 'SPSS Amos'),
        ('326', 'Stimulsoft'),
        ('327', 'Switching'),
        ('328', 'Telerik'),
        ('329', 'Veritas'),
        ('330', 'Veritas Bachup Exec'),
        ('331', 'Visio'),
        ('332', 'Visual Basic'),
        ('333', 'Visual Studio 2017'),
        ('334', 'VLAN'),
        ('335', 'VOIP'),
        ('336', 'Voip Gateways'),
        ('337', 'VPN'),
        ('338', 'WDS'),
        ('339', 'Web API'),
        ('340', 'Web Services'),
        ('341', 'Web-based communication'),
        ('342', 'Windows 2016'),
        ('343', 'Windows 7'),
        ('344', 'Windows Server'),
        ('345', 'Windows server 2016 '),
        ('346', 'Windows Server 2012 R2'),
        ('347', 'WinForms'),
        ('348', 'WSUS'),
        ('349', 'XHTML'),
        ('350', 'XML'),
        ('351', '1C Database'),
        ('352', 'CISCO CCNA'),
        ('353', 'VMware Server'),
        ('354', 'Windows Vista'),
        ('355', '3D MAX')
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    work_preparedness = models.CharField(verbose_name='Work preparedness', max_length=30, null=True, blank=True,
                                         choices=WORK_PREPAREDNESS, default='2')
    min_salary = models.IntegerField(verbose_name='Salary', null=True, blank=True)
    specialization = models.CharField(verbose_name='Specialization', max_length=30, null=True, blank=True)
    qualification = models.CharField(verbose_name='Qualification', max_length=10, null=True, blank=True,
                                     choices=QUALIFICATION)
    sphere = MultiSelectField(choices=SPHERE, max_choices=2, max_length=20, verbose_name='Sphere', null=True, blank=True)
    skills = MultiSelectField(choices=SKILL, max_choices=12, max_length=30, verbose_name='Skills', null=True, blank=True)
    remote_work = models.BooleanField(verbose_name='Remote work', default=False)
    date_created = models.DateTimeField(verbose_name='Create date', auto_now_add=True)

    def __str__(self):
        return str(self.user)


class WorkExperience(models.Model):
    SKILL = (
        ('1', 'ABAP'),
        ('2', 'ActiveMQ'),
        ('3', 'Ada programming'),
        ('4', 'Amazon Web Services'),
        ('5', 'Android'),
        ('6', 'Angular 2+'),
        ('7', 'AngularJS'),
        ('8', 'Ansible'),
        ('9', 'Apache Hive'),
        ('10', 'Apache Kafka'),
        ('11', 'Apache Pig'),
        ('12', 'Apache Spark'),
        ('13', 'ARM'),
        ('14', 'ASP.NET'),
        ('15', 'ASP.NET MVC'),
        ('16', 'Azure'),
        ('17', 'Backbone.js'),
        ('18', 'Bash'),
        ('19', 'Blockchain'),
        ('20', 'C'),
        ('21', 'C#'),
        ('22', 'C++'),
        ('23', 'CakePHP'),
        ('24', 'Cassandra'),
        ('25', 'Chef'),
        ('26', 'Cisco'),
        ('27', 'Clojure'),
        ('28', 'CoffeeScript'),
        ('29', 'Cordova'),
        ('30', 'Cross Platform Mobile'),
        ('31', 'Django'),
        ('32', 'Docker'),
        ('33', 'Drools'),
        ('34', 'Drupal'),
        ('35', 'Elasticsearch'),
        ('36', 'Elixir'),
        ('37', 'ELM'),
        ('38', 'Embedded Linux'),
        ('39', 'Ember.js'),
        ('40', 'Erlang'),
        ('41', 'ETL'),
        ('42', 'Ez Platform'),
        ('43', 'F#'),
        ('44', 'Flash'),
        ('45', 'Flask'),
        ('46', 'Flutter'),
        ('47', 'Fortinet'),
        ('48', 'Fortran'),
        ('49', 'FPGA'),
        ('50', 'Go'),
        ('51', 'Google Cloud Platform'),
        ('52', 'Google Data Studio'),
        ('53', 'Grails'),
        ('54', 'Grape'),
        ('55', 'Groovy'),
        ('56', 'Hadoop'),
        ('57', 'Haskell'),
        ('58', 'HBase'),
        ('59', 'Hibernate'),
        ('60', 'HTML/CSS'),
        ('61', 'Hyper-V'),
        ('62', 'Informatica'),
        ('63', 'Internet of Things'),
        ('64', 'Ionic'),
        ('65', 'iOS'),
        ('66', 'J2EE'),
        ('67', 'Java'),
        ('68', 'JavaFX'),
        ('69', 'JavaScript'),
        ('70', 'Jenkins'),
        ('71', 'Joomla'),
        ('72', 'jQuery'),
        ('73', 'Juniper'),
        ('74', 'Keras'),
        ('75', 'Kotlin'),
        ('76', 'Kubernetes'),
        ('77', 'LAN/WAN'),
        ('78', 'Laravel'),
        ('79', 'Liferay'),
        ('80', 'Linux'),
        ('81', 'Lisp'),
        ('82', 'Looker'),
        ('83', 'Magento'),
        ('84', 'Matlab'),
        ('85', 'Memcached'),
        ('86', 'Meteor'),
        ('87', 'MongoDB'),
        ('88', 'MySQL'),
        ('89', '.NET'),
        ('90', '.NET Core'),
        ('91', 'NLP'),
        ('92', 'Node.js'),
        ('93', 'Objective-C'),
        ('94', 'OCaml'),
        ('95', 'OpenGL'),
        ('96', 'OpenStack'),
        ('97', 'Oracle Database'),
        ('98', 'Pandas'),
        ('99', 'Pentaho'),
        ('100', 'Perl'),
        ('101', 'PHP'),
        ('102', 'Pixi.js'),
        ('103', 'Play'),
        ('104', 'PL/SQL'),
        ('105', 'Polymer'),
        ('106', 'PostgreSQL'),
        ('107', 'Power BI'),
        ('108', 'Prestashop'),
        ('109', 'Proxmox Virtual Environment'),
        ('110', 'Puppet'),
        ('111', 'Python'),
        ('112', 'Pytorch'),
        ('113', 'Qlik'),
        ('114', 'Qt'),
        ('115', 'R'),
        ('116', 'RabbitMQ'),
        ('117', 'ReactJS'),
        ('118', 'React Native'),
        ('119', 'Redis'),
        ('120', 'Redux'),
        ('121', 'Riot.js'),
        ('122', 'Ruby'),
        ('123', 'Ruby on Rails'),
        ('124', 'Rust'),
        ('125', 'SAS'),
        ('126', 'SASS'),
        ('127', 'Scala'),
        ('128', 'Scheme'),
        ('129', 'scikit-learn'),
        ('130', 'Selenium'),
        ('131', 'SEO'),
        ('132', 'Shopware'),
        ('133', 'Sinatra'),
        ('134', 'Solr'),
        ('135', 'Spring'),
        ('136', 'Spring Boot'),
        ('137', 'SPSS'),
        ('138', 'SQL'),
        ('139', 'SQL Server'),
        ('140', 'Stata'),
        ('141', 'Struts'),
        ('142', 'Swift'),
        ('143', 'Symfony'),
        ('144', 'Tableau'),
        ('145', 'Talend'),
        ('146', 'TCL'),
        ('147', 'TensorFlow'),
        ('148', 'Terraform'),
        ('149', 'Tomcat'),
        ('150', 'T-SQL'),
        ('151', 'TypeScript'),
        ('152', 'Unity'),
        ('153', 'Unix Shell Scripting'),
        ('154', 'VBA'),
        ('155', 'VB.NET'),
        ('156', 'Verilog'),
        ('157', 'VHDL'),
        ('158', 'VMWare vSphere'),
        ('159', 'Vue.js'),
        ('160', 'VxWorks'),
        ('161', 'WCF'),
        ('162', 'Windows'),
        ('163', 'Windows Mobile'),
        ('164', 'WordPress'),
        ('165', 'WPF'),
        ('166', 'x86 Assembly'),
        ('167', 'Xamarin'),
        ('168', 'Yii'),
        ('169', 'Zend Framework'),
        ('170', 'Microsoft Office Word'),
        ('171', 'Microsoft Office Excel'),
        ('172', 'Microsoft Office PowerPoint'),
        ('173', 'Microsoft Office Outlook'),
        ('174', 'Microsoft Office Project'),
        ('175', 'Microsoft Office Access'),
        ('176', 'Microsoft Office Visio'),
        ('177', 'Microsoft Office Sharepoint'),
        ('178', 'MS office applications'),
        ('179', '1C'),
        ('180', 'Active Directory'),
        ('181', 'Active Sync'),
        ('182', 'AD'),
        ('183', 'Adobe Acrobat'),
        ('184', 'Adobe after effects'),
        ('185', 'Adobe Audition'),
        ('186', 'Adobe Photoshop'),
        ('187', 'Adobe Premiere Pro'),
        ('188', 'Adobe Reader'),
        ('189', 'AJAX'),
        ('190', 'Android SDK'),
        ('191', 'Angular'),
        ('192', 'ANSYS'),
        ('193', 'Application Servers'),
        ('194', 'Arc GIS'),
        ('195', 'ArchiCAD'),
        ('196', 'Ariana'),
        ('197', 'ASP'),
        ('198', 'Asterisk'),
        ('199', 'Asterisk Server'),
        ('200', 'ASYCUDA'),
        ('201', 'AutoCAD'),
        ('202', 'AutoCAD Civil 3D'),
        ('203', 'Bootstrap'),
        ('204', 'Bulk Rename utility'),
        ('205', 'CATIA'),
        ('206', 'CMS'),
        ('207', 'Corel'),
        ('208', 'coreldraw'),
        ('209', 'Crystal Report'),
        ('210', 'CSS'),
        ('211', 'CSS3'),
        ('212', 'Data Deduplication'),
        ('213', 'Data warehouse'),
        ('214', 'Database performance tuning'),
        ('215', 'Devexpress'),
        ('216', 'DFS'),
        ('217', 'DHCP'),
        ('218', 'DNS'),
        ('219', 'eBudget'),
        ('220', 'Edge Server'),
        ('221', 'eDocument'),
        ('222', 'eflow'),
        ('223', 'eHRMS'),
        ('224', 'EJB 3.x'),
        ('225', 'Entity Framework'),
        ('226', 'eTreasury'),
        ('227', 'EViews'),
        ('228', 'Exchange'),
        ('229', 'Exchange Server'),
        ('230', 'Exchange(DAG)'),
        ('231', 'Ext JS'),
        ('232', 'extejs'),
        ('233', 'Fiber Optics'),
        ('234', 'Final Cut Studio'),
        ('235', 'Firewall'),
        ('236', 'Flexsys'),
        ('237', 'FMG'),
        ('238', 'FSRM'),
        ('239', 'FTP'),
        ('240', 'GeoServer'),
        ('241', 'Google Apps for Business'),
        ('242', 'GPO'),
        ('243', 'GPS'),
        ('244', 'Group policy'),
        ('245', 'Hibernate/JPA'),
        ('246', 'HTML'),
        ('247', 'HTML5'),
        ('248', 'IIS'),
        ('249', 'illustrator'),
        ('250', 'InDesign'),
        ('251', 'IPCC Inventory Software'),
        ('252', 'iSCSI '),
        ('253', 'JAVA EE'),
        ('254', 'java SDK'),
        ('255', 'Java Spring'),
        ('256', 'JBoss Aplication Server'),
        ('257', 'JBoss Seam Framework'),
        ('258', 'JMS'),
        ('259', 'JS'),
        ('260', 'JSF'),
        ('261', 'JSON'),
        ('262', 'Kerio Operator'),
        ('263', 'LINQ'),
        ('264', 'Lumion'),
        ('265', 'Lync'),
        ('266', 'Mac OS'),
        ('267', 'Magic X Audio Editing'),
        ('268', 'Magic X Music Macer'),
        ('269', 'Mail Server'),
        ('270', 'Max MSP'),
        ('271', 'MAXQDA'),
        ('272', 'Microsoft Active Directory'),
        ('273', 'Microsoft Exchange'),
        ('274', 'Microsoft Exchange 2013-2016'),
        ('275', 'Microsoft Exchange Servers Clustering'),
        ('276', 'Microsoft Expression Blend'),
        ('277', 'Microsoft Project Server'),
        ('278', 'Microsoft SQL Server Management Studio'),
        ('279', 'Microsoft Team Foundation Server '),
        ('280', 'Microsoft Visual Studio'),
        ('281', 'Mozilla Firefox'),
        ('282', 'Mplus'),
        ('283', 'MS Office Lync'),
        ('284', 'MS SQL'),
        ('285', 'MS SQL Server'),
        ('286', 'MVC'),
        ('287', 'MVC Core'),
        ('288', 'Mware vSphere 6.x'),
        ('289', 'Navision'),
        ('290', 'Network Administrator '),
        ('291', 'NTFS File Permission'),
        ('292', 'NVivo'),
        ('293', 'OneNote'),
        ('294', 'OOP'),
        ('295', 'OOP PHP'),
        ('296', 'Oracle'),
        ('297', 'Oracle 11g'),
        ('298', 'Oracle, XML'),
        ('299', 'ORIS'),
        ('300', 'ORIS Manager'),
        ('301', 'Outlook Anywhere '),
        ('302', 'Outlook Express'),
        ('303', 'PageMaker'),
        ('304', 'PDS'),
        ('305', 'Photoshop'),
        ('306', 'Power IP PBX Systems'),
        ('307', 'Premier Pro'),
        ('308', 'Project Server'),
        ('309', 'Publisher'),
        ('310', 'RA'),
        ('311', 'Revit'),
        ('312', 'RichFaces'),
        ('313', 'RichFaces/MyFaces'),
        ('314', 'Routing'),
        ('315', 'RS.GE'),
        ('316', 'SCCM'),
        ('317', 'SCDPM'),
        ('318', 'SCO'),
        ('319', 'SCOM'),
        ('320', 'SCVMM'),
        ('321', 'Share Permission'),
        ('322', 'SharePoint'),
        ('323', 'Sony Vegas'),
        ('324', 'Sound Forge'),
        ('325', 'SPSS Amos'),
        ('326', 'Stimulsoft'),
        ('327', 'Switching'),
        ('328', 'Telerik'),
        ('329', 'Veritas'),
        ('330', 'Veritas Bachup Exec'),
        ('331', 'Visio'),
        ('332', 'Visual Basic'),
        ('333', 'Visual Studio 2017'),
        ('334', 'VLAN'),
        ('335', 'VOIP'),
        ('336', 'Voip Gateways'),
        ('337', 'VPN'),
        ('338', 'WDS'),
        ('339', 'Web API'),
        ('340', 'Web Services'),
        ('341', 'Web-based communication'),
        ('342', 'Windows 2016'),
        ('343', 'Windows 7'),
        ('344', 'Windows Server'),
        ('345', 'Windows server 2016 '),
        ('346', 'Windows Server 2012 R2'),
        ('347', 'WinForms'),
        ('348', 'WSUS'),
        ('349', 'XHTML'),
        ('350', 'XML'),
        ('351', '1C Database'),
        ('352', 'CISCO CCNA'),
        ('353', 'VMware Server'),
        ('354', 'Windows Vista'),
        ('355', '3D MAX')
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    name = models.CharField(verbose_name='Company name', max_length=220, null=True)
    position = models.CharField(verbose_name='Position', max_length=200, null=True)
    location = models.CharField(verbose_name='Location', max_length=150, null=True)
    start_date = models.DateField(verbose_name='Start date', null=True)
    end_date = models.DateField(verbose_name='End date', null=True, blank=True)
    present = models.BooleanField(verbose_name='Present', default=False)
    responsibilities = models.TextField(verbose_name='Responsibilities', max_length=600, null=True, blank=True)
    skills = MultiSelectField(choices=SKILL, max_choices=12, max_length=255, verbose_name='skills', null=True)
    date_created = models.DateTimeField(verbose_name='Create date', auto_now_add=True)

    def __str__(self):
        return str(self.user)


class Education (models.Model):
    DEGREE = (
        ('1', "Bachelor's degree"),
        ('2', "Master's degree"),
        ('3', "Doctoral degree"),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    name = models.CharField(verbose_name='University name', max_length=220, null=True)
    faculty = models.CharField(verbose_name='Faculty', max_length=200, null=True)
    degree = models.CharField(verbose_name='Degree', max_length=1, choices=DEGREE, null=True)
    location = models.CharField(verbose_name='Location', max_length=150, null=True, blank=True)
    start_date = models.DateField(verbose_name='Start date', null=True)
    end_date = models.DateField(verbose_name='End date', null=True, blank=True)
    present = models.BooleanField(verbose_name='Present', default=False)
    specialization = models.TextField(verbose_name='Specialization', max_length=600, null=True, blank=True)
    date_created = models.DateTimeField(verbose_name='Create date', auto_now_add=True)

    def __str__(self):
        return str(self.user)


class MoreEducation (models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    name = models.CharField(verbose_name='Educational place name', max_length=220, null=True)
    course_name = models.CharField(verbose_name='Course name', max_length=255, null=True)
    theme = models.CharField(verbose_name='Theme', max_length=150, null=True)
    start_date = models.DateField(verbose_name='Start date', null=True)
    end_date = models.DateField(verbose_name='End date', null=True, blank=True)
    present = models.BooleanField(verbose_name='Present', default=False)
    about_course = models.TextField(verbose_name='About course', max_length=600, null=True, blank=True)
    date_created = models.DateTimeField(verbose_name='Create date', auto_now_add=True)

    def __str__(self):
        return str(self.user)


class Language (models.Model):
    LANGUAGES = (
        ('en', 'English'),
        ('fr', 'French'),
        ('de', 'German'),
        ('nl', 'Dutch'),
        ('ab', 'Abkhazian'),
        ('aa', 'Afar'),
        ('af', 'Afrikaans'),
        ('ak', 'Akan'),
        ('sq', 'Albanian'),
        ('am', 'Amharic'),
        ('ar', 'Arabic'),
        ('an', 'Aragonese'),
        ('hy', 'Armenian'),
        ('as', 'Assamese'),
        ('av', 'Avaric'),
        ('ae', 'Avestan'),
        ('ay', 'Aymara'),
        ('az', 'Azerbaijani'),
        ('bm', 'Bambara'),
        ('ba', 'Bashkir'),
        ('eu', 'Basque'),
        ('be', 'Belarusian'),
        ('bn', 'Bengali'),
        ('bi', 'Bislama'),
        ('bs', 'Bosnian'),
        ('br', 'Breton'),
        ('bg', 'Bulgarian'),
        ('my', 'Burmese'),
        ('ca', 'Catalan'),
        ('km', 'Central Khmer'),
        ('ch', 'Chamorro'),
        ('ce', 'Chechen'),
        ('ny', 'Chichewa'),
        ('zh', 'Chinese'),
        ('cv', 'Chuvash'),
        ('kw', 'Cornish'),
        ('co', 'Corsican'),
        ('cr', 'Cree'),
        ('hr', 'Croatian'),
        ('cs', 'Czech'),
        ('da', 'Danish'),
        ('dv', 'Divehi'),
        ('dz', 'Dzongkha'),
        ('eo', 'Esperanto'),
        ('et', 'Estonian'),
        ('ee', 'Ewe'),
        ('fo', 'Faroese'),
        ('fj', 'Fijian'),
        ('fi', 'Finnish'),
        ('ff', 'Fulah'),
        ('gd', 'Gaelic'),
        ('gl', 'Galician'),
        ('lg', 'Ganda'),
        ('ka', 'Georgian'),
        ('el', 'Greek'),
        ('gn', 'Guarani'),
        ('gu', 'Gujarati'),
        ('ht', 'Haitian'),
        ('ha', 'Hausa'),
        ('he', 'Hebrew'),
        ('hz', 'Herero'),
        ('hi', 'Hindi'),
        ('ho', 'Hiri Motu'),
        ('hu', 'Hungarian'),
        ('is', 'Icelandic'),
        ('io', 'Ido'),
        ('ig', 'Igbo'),
        ('id', 'Indonesian'),
        ('ia', 'Interlingua (International Auxiliary Language Association)'),
        ('ie', 'Interlingue'),
        ('iu', 'Inuktitut'),
        ('ik', 'Inupiaq'),
        ('ga', 'Irish'),
        ('it', 'Italian'),
        ('ja', 'Japanese'),
        ('jv', 'Javanese'),
        ('kl', 'Kalaallisut'),
        ('kn', 'Kannada'),
        ('kr', 'Kanuri'),
        ('ks', 'Kashmiri'),
        ('kk', 'Kazakh'),
        ('ki', 'Kikuyu'),
        ('rw', 'Kinyarwanda'),
        ('ky', 'Kirghiz'),
        ('kv', 'Komi'),
        ('kg', 'Kongo'),
        ('ko', 'Korean'),
        ('kj', 'Kuanyama'),
        ('ku', 'Kurdish'),
        ('lo', 'Lao'),
        ('la', 'Latin'),
        ('lv', 'Latvian'),
        ('li', 'Limburgan'),
        ('ln', 'Lingala'),
        ('lt', 'Lithuanian'),
        ('lu', 'Luba-Katanga'),
        ('lb', 'Luxembourgish'),
        ('mk', 'Macedonian'),
        ('mg', 'Malagasy'),
        ('ms', 'Malay'),
        ('ml', 'Malayalam'),
        ('mt', 'Maltese'),
        ('gv', 'Manx'),
        ('mi', 'Maori'),
        ('mr', 'Marathi'),
        ('mh', 'Marshallese'),
        ('mo', 'Moldavian'),
        ('mn', 'Mongolian'),
        ('na', 'Nauru'),
        ('nv', 'Navajo'),
        ('nd', 'Ndebele, North'),
        ('nr', 'Ndebele, South'),
        ('ng', 'Ndonga'),
        ('ne', 'Nepali'),
        ('se', 'Northern Sami'),
        ('nw', 'Norwegian'),
        ('oc', 'Occitan'),
        ('oj', 'Ojibwa'),
        ('or', 'Oriya'),
        ('om', 'Oromo'),
        ('os', 'Ossetian'),
        ('pi', 'Pali'),
        ('pa', 'Panjabi'),
        ('fa', 'Persian'),
        ('pl', 'Polish'),
        ('pt', 'Portuguese'),
        ('ps', 'Pushto'),
        ('qu', 'Quechua'),
        ('ro', 'Romanian'),
        ('rm', 'Romansh'),
        ('rn', 'Rundi'),
        ('ru', 'Russian'),
        ('sm', 'Samoan'),
        ('sg', 'Sango'),
        ('sa', 'Sanskrit'),
        ('sc', 'Sardinian'),
        ('sr', 'Serbian'),
        ('sn', 'Shona'),
        ('ii', 'Sichuan Yi'),
        ('sd', 'Sindhi'),
        ('si', 'Sinhala'),
        ('sk', 'Slovak'),
        ('sl', 'Slovenian'),
        ('so', 'Somali'),
        ('st', 'Sotho, Southern'),
        ('es', 'Spanish'),
        ('su', 'Sundanese'),
        ('sw', 'Swahili'),
        ('ss', 'Swati'),
        ('sv', 'Swedish'),
        ('tl', 'Tagalog'),
        ('ty', 'Tahitian'),
        ('tg', 'Tajik'),
        ('ta', 'Tamil'),
        ('tt', 'Tatar'),
        ('te', 'Telugu'),
        ('th', 'Thai'),
        ('bo', 'Tibetan'),
        ('ti', 'Tigrinya'),
        ('to', 'Tonga (Tonga Islands)'),
        ('ts', 'Tsonga'),
        ('tn', 'Tswana'),
        ('tr', 'Turkish'),
        ('tk', 'Turkmen'),
        ('tw', 'Twi'),
        ('ug', 'Uighur'),
        ('uk', 'Ukrainian'),
        ('ur', 'Urdu'),
        ('uz', 'Uzbek'),
        ('ve', 'Venda'),
        ('vi', 'Vietnamese'),
        ('vo', 'Volapük'),
        ('wa', 'Walloon'),
        ('cy', 'Welsh'),
        ('fy', 'Western Frisian'),
        ('wo', 'Wolof'),
        ('xh', 'Xhosa'),
        ('yi', 'Yiddish'),
        ('yo', 'Yoruba'),
        ('za', 'Zhuang'),
        ('zu', 'Zulu'),
    )
    LEVELS = (
        ('1', 'C2'),
        ('2', 'C1'),
        ('3', 'B2'),
        ('4', 'B1'),
        ('5', 'A2'),
        ('6', 'A1'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    language = models.CharField(verbose_name='Language', max_length=2, choices=LANGUAGES)
    level = models.CharField(verbose_name='Level', max_length=1, choices=LEVELS)
    date_created = models.DateTimeField(verbose_name='Create date', auto_now_add=True)

    def __str__(self):
        return str(self.user)


class Contact (models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    phone = models.CharField(verbose_name='Phone', max_length=150, null=True, blank=True)
    email = models.CharField(verbose_name='Email', max_length=150, null=True, blank=True)
    website = models.CharField(verbose_name='Website', max_length=150, null=True, blank=True)
    facebook = models.CharField(verbose_name='Facebook', max_length=150, null=True, blank=True)
    github = models.CharField(verbose_name='Github', max_length=150, null=True, blank=True)
    twitter = models.CharField(verbose_name='Twitter', max_length=150, null=True, blank=True)
    date_created = models.DateTimeField(verbose_name='Create date', auto_now_add=True)

    def __str__(self):
        return str(self.user)
