# Generated by Django 3.0.4 on 2020-04-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20200428_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='Seen'),
        ),
    ]
