# Generated by Django 3.0.4 on 2020-04-28 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_message_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Seen date'),
            preserve_default=False,
        ),
    ]
