# Generated by Django 3.0.4 on 2020-04-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_message_seen_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='receiver_delete',
            field=models.BooleanField(default=False, verbose_name='Receiver delete'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='starter_delete',
            field=models.BooleanField(default=False, verbose_name='Starter delete'),
        ),
    ]
