# Generated by Django 3.0.4 on 2020-03-30 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=30, unique=True, verbose_name='Url field')),
                ('organization_name', models.CharField(max_length=30, null=True, verbose_name='Organization name')),
                ('organization_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization phone')),
                ('organization_email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Organization email')),
                ('organization_alter_names', models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization alternative names')),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('organization_header_logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Header logo')),
                ('organization_about', models.TextField(blank=True, max_length=250, null=True, verbose_name='About organization')),
                ('organization_specialization', models.CharField(blank=True, max_length=70, null=True, verbose_name='Organization specialization')),
                ('organization_website', models.CharField(blank=True, max_length=100, null=True, verbose_name='website')),
                ('organization_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization address')),
                ('number_of_employees', models.CharField(blank=True, choices=[('1', '1'), ('10', '1-10'), ('100', '10-100'), ('1000', '100-1000'), ('5000', '1000+')], max_length=100, null=True, verbose_name='Number of employees')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
