# Generated by Django 3.0.4 on 2020-03-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=40, verbose_name='last name')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile picture')),
                ('about_me', models.TextField(blank=True, max_length=250, null=True, verbose_name='about me')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='birth_day')),
                ('living_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='living city')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='website')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='website')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
