# Generated by Django 3.0.4 on 2020-04-17 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ManyToManyField(to='accounts.Skills')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_preparedness', models.CharField(blank=True, choices=[('1', 'Not looking for work'), ('2', 'Looking for work'), ('3', 'Open to offers')], default='2', max_length=30, null=True, verbose_name='Work preparedness')),
                ('min_salary', models.IntegerField(blank=True, null=True, verbose_name='Salary')),
                ('specialization', models.CharField(max_length=30, null=True, verbose_name='Organization name')),
                ('qualification', models.CharField(choices=[('1', 'Intern'), ('2', 'Junior'), ('3', 'Middle'), ('4', 'Senior'), ('5', 'Lead')], max_length=10, null=True, verbose_name='Qualification')),
                ('sphere', models.CharField(choices=[('1', 'Backend'), ('2', 'Frontend'), ('3', 'Design'), ('4', 'Administration'), ('5', 'Analytics'), ('6', 'Testing'), ('7', 'Management'), ('8', 'Marketing'), ('9', 'Telekom'), ('10', 'Sales'), ('11', 'Applications'), ('12', 'Software'), ('13', 'Other')], max_length=20, null=True, verbose_name='Work type')),
                ('remote_work', models.BooleanField(default=False, verbose_name='Remote work')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
