# Generated by Django 3.0.4 on 2020-04-17 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_skills_specialization_userskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='specialization',
            field=models.CharField(max_length=30, null=True, verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='sphere',
            field=models.CharField(choices=[('1', 'Backend'), ('2', 'Frontend'), ('3', 'Design'), ('4', 'Administration'), ('5', 'Analytics'), ('6', 'Testing'), ('7', 'Management'), ('8', 'Marketing'), ('9', 'Telekom'), ('10', 'Sales'), ('11', 'Applications'), ('12', 'Software'), ('13', 'Other')], max_length=20, null=True, verbose_name='Sphere'),
        ),
        migrations.RemoveField(
            model_name='userskills',
            name='skill',
        ),
        migrations.AddField(
            model_name='userskills',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Skills'),
        ),
        migrations.RemoveField(
            model_name='userskills',
            name='user',
        ),
        migrations.AddField(
            model_name='userskills',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
