# Generated by Django 3.0.4 on 2020-04-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200417_2033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RenameModel(
            old_name='UserSkills',
            new_name='UserSkill',
        ),
    ]
