# Generated by Django 3.0.4 on 2020-04-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200417_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='qualification',
            field=models.CharField(blank=True, choices=[('1', 'Intern'), ('2', 'Junior'), ('3', 'Middle'), ('4', 'Senior'), ('5', 'Lead')], max_length=10, null=True, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='sphere',
            field=models.CharField(blank=True, choices=[('1', 'Backend'), ('2', 'Frontend'), ('3', 'Design'), ('4', 'Administration'), ('5', 'Analytics'), ('6', 'Testing'), ('7', 'Management'), ('8', 'Marketing'), ('9', 'Telekom'), ('10', 'Sales'), ('11', 'Applications'), ('12', 'Software'), ('13', 'Other')], max_length=20, null=True, verbose_name='Sphere'),
        ),
    ]
