# Generated by Django 3.0.4 on 2020-04-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200420_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='sphere',
            field=models.CharField(blank=True, choices=[('1', 'Back-End'), ('2', 'Front-End'), ('3', 'Full Stack'), ('4', 'Design'), ('5', 'Administration'), ('6', 'Analytics'), ('7', 'Testing'), ('8', 'Management'), ('9', 'Marketing'), ('10', 'Telekom'), ('11', 'Sales'), ('12', 'Applications'), ('13', 'Software'), ('14', 'Other')], max_length=20, null=True, verbose_name='Sphere'),
        ),
    ]
