# Generated by Django 3.0.4 on 2020-04-20 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200420_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create date'),
            preserve_default=False,
        ),
    ]
