# Generated by Django 3.0.4 on 2020-04-22 19:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userskill_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='sphere',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Back-End'), ('2', 'Front-End'), ('3', 'Full Stack'), ('4', 'Design'), ('5', 'Administration'), ('6', 'Analytics'), ('7', 'Testing'), ('8', 'Management'), ('9', 'Marketing'), ('10', 'Telekom'), ('11', 'Sales'), ('12', 'Applications'), ('13', 'Software'), ('14', 'Other')], max_length=150, null=True, verbose_name='Sphere'),
        ),
    ]
