# Generated by Django 3.0.4 on 2020-04-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_auto_20200423_1932'),
        ('accounts', '0012_specialization_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
    ]
