# Generated by Django 3.0.4 on 2020-04-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200425_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('1', "Bachelor's degree"), ('2', "Master's degree"), ('3', 'Doctoral degree')], max_length=1, null=True, verbose_name='Degree'),
        ),
    ]
