# Generated by Django 3.0.4 on 2020-04-25 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_education_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, null=True, verbose_name='Educational place name')),
                ('course_name', models.CharField(max_length=255, null=True, verbose_name='Course name')),
                ('theme', models.CharField(max_length=150, null=True, verbose_name='Theme')),
                ('start_date', models.DateField(null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('present', models.BooleanField(default=False, verbose_name='Present')),
                ('about_course', models.TextField(blank=True, max_length=600, null=True, verbose_name='About course')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
