# Generated by Django 3.0.4 on 2020-04-14 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0004_auto_20200414_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='bonuses',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Bonuses'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='instructions',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Instructions'),
        ),
        migrations.CreateModel(
            name='VacancyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.Vacancy')),
            ],
        ),
    ]
