# Generated by Django 3.0.4 on 2020-04-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_auto_20200414_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyresponse',
            name='qualification',
            field=models.CharField(choices=[('1', 'Submitted'), ('2', 'Accepted'), ('3', 'Marked'), ('4', 'Declined')], default='1', max_length=10, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(max_length=4000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='sphere',
            field=models.CharField(choices=[('1', 'Backend'), ('2', 'Frontend'), ('3', 'Design'), ('4', 'Administration'), ('5', 'Analytics'), ('6', 'Testing'), ('7', 'Management'), ('8', 'Marketing'), ('9', 'Telekom'), ('10', 'Sales'), ('11', 'Applications'), ('12', 'Software'), ('13', 'Other')], max_length=20, null=True, verbose_name='Work type'),
        ),
    ]
