# Generated by Django 3.0.4 on 2020-04-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_auto_20200415_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyresponse',
            name='qualification',
        ),
        migrations.AddField(
            model_name='vacancyresponse',
            name='status',
            field=models.CharField(choices=[('1', 'Submitted'), ('2', 'Accepted'), ('3', 'Marked'), ('4', 'Declined')], default='1', max_length=10, verbose_name='Status'),
        ),
    ]
