# Generated by Django 3.0.4 on 2020-04-21 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userskill_date_created'),
        ('vacancies', '0007_auto_20200415_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancySkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Skill')),
                ('vacancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.Vacancy')),
            ],
        ),
    ]
